version: "3"
service:
    app:
        container_name: simple_chat
        restart: always
        build: .
        port:
            - "8000:3000"
        links:
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - "27018:27017"