import { PartialTheme } from '@fluentui/react';

export const dark: PartialTheme = {
    palette: {
        themePrimary: '#09b1bd',
        themeLighterAlt: '#000708',
        themeLighter: '#021c1e',
        themeLight: '#033539',
        themeTertiary: '#066a71',
        themeSecondary: '#089ca6',
        themeDarkAlt: '#1cb8c3',
        themeDark: '#39c3cd',
        themeDarker: '#66d2da',
        neutralLighterAlt: '#2b3137',
        neutralLighter: '#32393f',
        neutralLight: '#3e454c',
        neutralQuaternaryAlt: '#454d54',
        neutralQuaternary: '#4b535b',
        neutralTertiaryAlt: '#666e77',
        neutralTertiary: '#f0eeee',
        neutralSecondary: '#f2f1f1',
        neutralPrimaryAlt: '#f5f4f4',
        neutralPrimary: '#e8e6e6',
        neutralDark: '#faf9f9',
        black: '#fcfcfc',
        white: '#24292e',
    },
};
export const light: PartialTheme = {
    palette: {
        themePrimary: '#09b1bd',
        themeLighterAlt: '#000708',
        themeLighter: '#021c1e',
        themeLight: '#033539',
        themeTertiary: '#066a71',
        themeSecondary: '#089ca6',
        themeDarkAlt: '#1cb8c3',
        themeDark: '#39c3cd',
        themeDarker: '#66d2da',
        neutralLighterAlt: '#e9e7e7',
        neutralLighter: '#eae8e8',
        neutralLight: '#ebe9e9',
        neutralQuaternaryAlt: '#eceaea',
        neutralQuaternary: '#edebeb',
        neutralTertiaryAlt: '#f0eeee',
        neutralTertiary: '#aab1b8',
        neutralSecondary: '#9199a1',
        neutralPrimaryAlt: '#79818a',
        neutralPrimary: '#24292e',
        neutralDark: '#4c545c',
        black: '#373e45',
        white: '#e8e6e6',
    },
};

export default light;
